# https://hub.docker.com/r/marctv/minecraft-papermc-server
services:
  minecraft:
    image: marctv/minecraft-papermc-server:latest
    restart: always
    container_name: minecraft
    environment:
      - MEMORYSIZE=1G
      - PAPERMC_FLAGS=""
    volumes:
      - /mnt/minecraft-data:/data:rw
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    stdin_open: true
    tty: true
